tidev/ioslib

README.md, package.json
https://jira.appcelerator.org/browse/TIMOB-18538
=> [TIMOB-18538] Update node-ios-device for Node 0.12 compatibility

lib/simulator.js, package.json
JIRA: https://jira.appcelerator.org/browse/TIMOB-23146
Fix detection of watchapp installed state on Xcode 7.3
=> [TIMOB-23146] iOS/WatchOS: Installing to Simulators hangs since Xcode 7.3

.gitignore, .npmignore, index.js, lib/teams.js, lib/xcode.js, package.json, test/test-ioslib.js, test/test-teams.js, test/test-xcode.js
https://jira.appcelerator.org/browse/TIMOB-23549
[TIMOB-23549] Fixed detection of WatchOS simulators to include global sims. Added detection of AppleTV SDKs and sims. Added top-level detection of teams based on provisioning profiles and Xcode teams.
=> [TIMOB-23549] Fixed detection of WatchOS simulators to include global sims.

lib/simulator.js
JIRA: https://jira.appcelerator.org/browse/TIMOB-23620
I adopted the pairings Xcode allows you to make within its Device Manager
=> [TIMOB-23620] Add device pair compatibility for Xcode 8

lib/xcode.js, package-lock.json, package.json
https://jira.appcelerator.org/browse/TIMOB-26426
Having this here causes ioslib to state that every xcode >=6.0.0 is supported, which I'm fairly sure we don't want.
=> [TIMOB-26426] Remove hardcoded support for xcode >=6

lib/simctl.js, lib/simulator.js, lib/xcode.js, package.json
Works.
EDITED
Ticket: https://jira.appcelerator.org/browse/TIMOB-27124
=> feat: support Xcode 11

.travis.yml, CHANGELOG.md, package.json, src/devices.js, src/provisioning.js, src/simulator.js, test/test-devices.js, yarn.lock
BREAKING CHANGE(dep): Upgraded to node-ios-device v2.
BREAKING CHANGE(simulator): iOS Simulator watch companion lookup map.
fix(simulator): Added check for the existence of the simulator device directory before walking.
chore: Updated npm deps.
=> v3 with major breaking changes

lib/xcode.js
Xcode 11 Beta 3 seems to have changed the `CoreSimulator` path for iOS and WatchOS.
=> fix: properly detect Xcode 11 CoreSimulator directory

Jenkinsfile, src/certs.js
=> feat(certs): support detecting generic apple development certificates

lib/certs.js
=> feat(certs): support detecting apple certs

CHANGELOG.md, bin/ioslib, package.json, src/simulator.js, yarn.lock
fix(simulator): Fixed watchOS sim semver ranges for device pair compatibility lookup and added a truthiness check in case we ever need to blacklist a version.
fix(simulator): Added 'simctl' and 'simualator' executables to simulator info handles.
fix(cli): Fixed simulator info to display generated data instead of just the unsorted sims.
chore: Updated dependencies.
=> Simulator fixes

CHANGELOG.md, bin/ioslib, package.json, src/simulator.js, yarn.lock
fix(simulator): Fixed watchOS sim semver ranges for device pair compatibility lookup and added a truthiness check in case we ever need to blacklist a version.
fix(simulator): Added 'simctl' and 'simualator' executables to simulator info handles.
fix(cli): Fixed simulator info to display generated data instead of just the unsorted sims.
chore: Updated dependencies.
=> Simulator fixes (backport)

lib/simulator.js, lib/xcode.js
https://jira.appcelerator.org/browse/TIMOB-27463
=> fix(ios): Fixed semver ranges

lib/simulator.js
When adding the global simulator runtimes into the runtime info, set the executable information only when we have it and we know the xcode version and simulator are compatible
Fixes [TIMOB-27490](https://jira.appcelerator.org/browse/TIMOB-27490)
=> fix: add executable information to simulator when looping over xcodes

CHANGELOG.md, package.json, src/xcode.js
The code was applying the iOS runtime filtering to watchOS runtimes causing the watchOS runtimes to not be detected.
https://jira.appcelerator.org/browse/DAEMON-306
=> fix(xcode): detect all sim runtimes and only remove them after detection

lib/simulator.js, lib/xcode.js
https://jira.appcelerator.org/browse/TIMOB-27647
Fixed a several year old bug where the iPhone Simulator SDK was treated as a iOS Simulator _version_. This means you could have a sim sdk of 13.2.2, but the available ios sim is actually 13.3. In other words, the iPhone Simulator SDK is an apple and the iOS Sim version is an orange and ioslib has been trying to associate the two.
This fix correctly pairs Xcodes with simulators using sim runtimes.
This PR also fixes a handful of other small bugs:
* Fixed iOS semver range causing incorrect iOS and watchOS SDKs from being selectable... I believe this only affects users with more than one Xcode installed.
* Fixed bug where global watchOS sim runtimes were being filtered out because they were being compared as if they were iOS sim versions.
* …
=> fix: Correctly detect compatible sims so that a sim can be auto-selected

lib/simulator.js, package-lock.json, package.json
Appears the new iOS 15 sims have a symlink'd directory which ioslib does not like at all. So lets not walk those directories
Fixes TIMOB-28498
=> fix(simulator): do not follow symlinks when walking dataDir to cleanup log files

lib/simulator.js, test/test-simulator.js
[Ticket](https://jira.appcelerator.org/browse/TIMOB-28542)
This is an attempt at fixing the handling of logged JSON objects which now no longer show fully due to the changes in b06258a7558e544a7c4bc482f93bb6b7c03072e9
We process the log line by line so for each line below will be processed individually and will be ignored as it does not include the app name.
Given that you can do things like `console.log('foo', { an: 'object' }, 'foo')` I'm not sure of a better way than using startsWith/endsWith, and I think it's possible this might fall down when combined with something like a `console.group`
```
2021-09-29 15:11:03.550 ticreateapp[45017:3689822] [INFO] {
x: [33m133[39m,
y: [33m477.6666564941406[39m,
bubbles: [33mtrue[39m,
type: [32m'click'[39m,
source: Object { 
[barColor]: …
```
=> fix(simulator): add in detection for processing logged json objects

lib/xcode.js
Ensure xcode.js change that uses replaceAll can run on node 14.x by replacing replaceAll with replace and a regex pattern instead
=> fix: ensure xcode.js change can run on node 14.x

lib/provisioning.js
Profiles are now found, also in combination with VSCode-Extension PR https://github.com/tidev/vscode-titanium/pull/1173
=> fix: supports now also MacCatalyst .provisioningprofile and iOS .mobileprovision

lib/simulator.js, package-lock.json, package.json
Xcode does not auto-create Simulators anymore. Before a long-term solution is added (fetch sims, fetch runtimes, create and link sim), this will resolve all user questions regarding this question already. I am not even sure if we should auto-create them at all, as Xcode offers the perfect UI to list, preview, create and link Simulators already.
=> chore: add help text to assist when no Simulators are available

lib/simctl.js, package-lock.json, package.json
This PR fixes an issue for Xcode 16+ and `ti build` (not happening with LiveView) where the app would launch in an corrupted state after an incremental build. It seems to be a Xcode 16 regression that can be fixed by making sure to terminate running processes before installing the new build.
Reported by @max87za via https://github.com/tidev/titanium-sdk/issues/14121
1. Run an app with Xcode 16, e.g. `ti build -p ios`
2. Keep the simulator open and run the app again
Expected behavior: The new version is installed
Actual behavior: The app hangs in the old state or gets partially updated
=> fix: make sure to terminate running processes before launching app

lib/xcode.js
Wow, this was HARD to find..but this is what's happening:
- Xcode 16.3 does not embed the device types (`<device>.simdevicetype`) under `Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/DeviceTypes` anymore, in fact, the whole `CoreSimulator` folder was nuked
- Luckily, `xcrun simctl list --json` already returns them pre-formatted, so Apple likely decided to sunset the additional files
- We now use that API to fetch the required model identifier and Watch support state
- The following call (to check the devices from simctl) can then be merged into one loop to do all work in one step
Note: ~~I have ditched the legacy code, so ioslib will only be compatible with Xcode 16.3+. As earlier versions use an earlier ioslib version anyway, I don't …
=> fix: use “simctl list” to fetch device types, not file i/o
