lib/simulator.js
package.json

JIRA: https://jira.appcelerator.org/browse/TIMOB-19518

[TIMOB-19518] (5_0_X) Made uninstalling the app a flag that defaults to false

---

lib/simulator.js
package.json

https://jira.appcelerator.org/browse/TIMOB-23865

[TIMOB-23865] Fixed device pair compat lookup.

---

lib/simulator.js
lib/xcode.js
package.json

https://jira.appcelerator.org/browse/TIMOB-23894

[TIMOB-23894] Fixed handling of ios-version when choosing an iOS Simulator

---

lib/simulator.js
package.json

https://jira.appcelerator.org/browse/TIMOB-24227

v1.1.1. Fixed small but with booted flag.

---

lib/simulator.js
package.json

v1.2.1
[TIMOB-24525] Fixed bug detecting simulators when Xcode is not installed.

v1.2.1 - Fixed bug detecting simulators when Xcode is not installed.

---

lib/simulator.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-25320
Do not attempt to run simctl if we have a selectedXcode but the EULA is not accepted

[TIMOB-25320] Fix bug when xcode eula is not accepted

---

Jenkinsfile

Part of https://jira.appcelerator.org/browse/DAEMON-202
Reinstates Jenkins to run the unit tests on OSX. No changes needed to the tests here to get a passing build

Reintroduce Jenkins

---

lib/xcode.js
package-lock.json
package.json

https://jira.appcelerator.org/browse/TIMOB-26209

[TIMOB-26209] Reverted 20e12b5. Improved Xcode EULA issue handling.

---

lib/simctl.js
lib/simulator.js
package.json

chore: v1.7.9
https://jira.appcelerator.org/browse/TIMOB-27124

fix: Fixed 'isAvailable' falsey checks.

---

lib/certs.js
package-lock.json
package.json

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27330
Requires https://github.com/appcelerator/titanium_mobile/pull/11133

chore: expose team-id in certificate info

---

src/certs.js

feat(certs): support detecting generic apple development certificates

---

lib/simctl.js
lib/simulator.js
package-lock.json
package.json

https://jira.appcelerator.org/browse/TIMOB-27360

fix(sim): added support for installing watch apps using Xcode 11.

---

lib/simulator.js
package.json

fix: Chop sim patch segment to match sim runtime version (fixes TIMOB-27582).
https://jira.appcelerator.org/browse/TIMOB-27582

Fix patch versioned sims

---

CHANGELOG.md
package.json
src/xcode.js
yarn.lock

feat(xcode): Added 'userLicenseFile' path.

---

package.json
src/simulator.js

[TIMOB-28466](https://jira.appcelerator.org/browse/TIMOB-28466)
This updates the compatibility table for 4.x, the other PRs will be made once this is approved/merged

[master] Update Xcode compatibility table

---

lib/xcode.js
package-lock.json
package.json

[1_7_X] feat: add lookup table for xcode 13

---

package.json
src/simulator.js

[2_x] feat: add lookup table for xcode 13

---

lib/simulator.js
package-lock.json
package.json

fix(simulator): do not follow symlinks when finding log file

---

lib/simulator.js
package-lock.json
package.json

Fixes [TIMOB-28531](https://jira.appcelerator.org/browse/TIMOB-28531)

fix(simulator): error if EULA is not accepted for selected xcode

---

lib/simulator.js
package-lock.json
package.json

These are already application specific logs, so processing them further is pointless and just causes us to lose information
Fixes TIMOB-28549

fix(simulator): do not process the lines in a log file

---

src/simulator.js

feat: support Xcode 14 mappings (2_X)

---

package-lock.json
package.json

update node-ios-device to 1.11.0

chore: update node-ios-device

---

package-lock.json
package.json

chore: node-ios-device update
